version: '2.3'
services:
  service:
    image: andimenge/movie-favs:525f263ec4e5949499911c415024cbecccb1fb71
    init: true
    scale: 1
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=movie-favs-service' # backend name
      - 'traefik.port=3000'
      - 'traefik.frontend.rule=Host:movies.andimenge.de;PathPrefixStrip:/api'
      - 'traefik.docker.network=loadbalancer'
    environment:
      - MONGO_DB_HOST=mongodb
      - AUTH_KEY=${AUTH_KEY}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - TZ=Europe/Berlin
      - NODE_ENV=production
    cpu_count: 1
    mem_reservation: 100m
    mem_limit: '1500000000'
    restart: always
    depends_on:
      - mongodb
    networks:
      - loadbalancer
      - default

  mongodb: # mongo port 27017
    image: 'mongo:4-xenial'
    init: true
    environment:
      - TZ=Europe/Berlin
    # - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USER}
    # - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASS}
    volumes:
      - '/home/docker/data/movie-favs/mongo:/data/db'
    labels:
      - traefik.enable=false
    restart: always
    mem_reservation: 500m
    mem_limit: '20000000000'

  s3:
    image: minio/minio
    command: ['server', '/data']
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    volumes:
      - /home/docker/data/movie-favs/minio:/data/
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=movie-favs-s3' # backend name
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:data.andimenge.de'
      - 'traefik.frontend.passHostHeader=true'
      - 'traefik.docker.network=loadbalancer'
    restart: always
    mem_reservation: 500m
    mem_limit: '20000000000'
    networks:
      - loadbalancer
      - default

networks:
  loadbalancer:
    external: true
